=== AlexRA95/Proyectos/HTML2024/2ºEVA/schema_xsd/ejercicios_clase/ej8_v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fichasFamosos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ficha" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="iniciales" type="ini">
                            </xs:element>
                            <xs:element name="edad" type="xs:integer"></xs:element>
                            <xs:element name="iniciales-al-reves" type="ini">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="ini">
        <xs:restriction base="xs:string">
             <xs:pattern value="[A-Z][A-Z][A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AlexRA95/Proyectos/HTML2024/2ºEVA/schema_xsd/ejercicios_clase/ej8.xml
<?xml version="1.0" encoding="UTF-8"?>
<fichasFamosos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ej8_v2.xsd">
    <ficha>
        <nombre>Ana Sanz Tin</nombre>
        <iniciales>AST</iniciales>
        <edad>22</edad>
        <iniciales-al-reves>TSA</iniciales-al-reves>
    </ficha>
    <ficha>
        <nombre>Iker Rubio Mol</nombre>
        <iniciales>IRM</iniciales>
        <edad>23</edad>
        <iniciales-al-reves>MRI</iniciales-al-reves>
    </ficha>
</fichasFamosos>
