<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paneles_de_vuelo [
    <!ELEMENT paneles_de_vuelo (aeropuerto)*>
    <!ELEMENT aeropuerto (nombre,vuelos,fecha)*>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT vuelos (vuelo)+>
    <!ELEMENT vuelo (diario?,origen,destino,hora_salida,hora_llegada)>
        <!ATTLIST vuelo codigo ID #REQUIRED>
        <!ATTLIST vuelo estado (C | E | R) "E">
        <!ELEMENT diario EMPTY>
        <!ELEMENT origen (#PCDATA)>
        <!ELEMENT destino (#PCDATA)>
        <!ELEMENT hora_salida (#PCDATA)>
        <!ELEMENT hora_llegada (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    
]>

<paneles_de_vuelo>
    <aeropuerto>
        <nombre>Aeropuerto JFK</nombre>
        <vuelos>
            <vuelo codigo="V22" estado="R">
                <diario/>
                <origen> New York</origen>
                <destino>Chicago</destino>
                <hora_salida>9:30</hora_salida>
                <hora_llegada> 11:30</hora_llegada>
            </vuelo>
            <vuelo codigo="V23" estado="C">
                <origen>New York</origen>
                <destino>Miami</destino>
                <hora_salida> 10:15</hora_salida>
                <hora_llegada>11:15</hora_llegada>
            </vuelo>
        </vuelos>
        <fecha>20-01-2024</fecha>
    </aeropuerto>
</paneles_de_vuelo>