=== AlexRA95/Proyectos/HTML2024/2ºEVA/xml_dtd/factura/factura.dtd
<!ELEMENT facturas (factura)*>
<!ATTLIST facturas xmlns:e CDATA #FIXED "http://alex.org/emisor">
<!ATTLIST facturas xmlns:c CDATA #FIXED "http://alex.org/cliente">
    <!ELEMENT factura (datos_emisor, datos_cliente, detalle_factura)>
        <!ATTLIST factura numero CDATA #REQUIRED>
        <!ATTLIST factura fecha CDATA #REQUIRED>
        <!ELEMENT datos_emisor (e:nombre,e:cif,e:telefono)>
            <!ELEMENT e:nombre (#PCDATA)>
            <!ELEMENT e:cif (#PCDATA)>
            <!ELEMENT e:telefono (#PCDATA)>
        <!ELEMENT datos_cliente (c:nombre,c:cif,c:telefono)>
            <!ELEMENT c:nombre (#PCDATA)>
            <!ELEMENT c:cif (#PCDATA)>
            <!ELEMENT c:telefono (#PCDATA)>
        <!ELEMENT detalle_factura (articulo)+>
            <!ATTLIST detalle_factura importe CDATA #REQUIRED>
            <!ELEMENT articulo (descripcion,cantidad,oferta?,pvp)>
                <!ATTLIST articulo codigo_articulo ID #REQUIRED>
                <!ATTLIST articulo tipo (Libro| DVD | Varios) #IMPLIED>
                <!ELEMENT descripcion (#PCDATA)>
                <!ELEMENT cantidad (#PCDATA)>
                <!ELEMENT oferta EMPTY>
                <!ELEMENT pvp (#PCDATA)>

=== AlexRA95/Proyectos/HTML2024/2ºEVA/xml_dtd/factura/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "factura.dtd">

<facturas 
xmlns:e="http://alex.org/emisor"
xmlns:c="http://alex.org/cliente">
    <factura numero="27" fecha="2024-01-20">
        <datos_emisor>
            <e:nombre>Librería Pérez</e:nombre>
            <e:cif> 44555666B</e:cif>
            <e:telefono>777888999</e:telefono>
        </datos_emisor>
        <datos_cliente>
            <c:nombre>Biblioteca Mérida</c:nombre>
            <c:cif>33111222A</c:cif>
            <c:telefono>333999444</c:telefono>
        </datos_cliente>
        <detalle_factura importe="85">
            <articulo codigo_articulo="AW7" tipo="Libro">
                <descripcion>Analítica Web 2.0</descripcion>
                <cantidad>1</cantidad>
                <oferta/>
                <pvp>25</pvp>
            </articulo>
            <articulo codigo_articulo="CP5" tipo="DVD">
                <descripcion>Curso de HTML</descripcion>
                <cantidad>2</cantidad>
                <pvp>30</pvp>
            </articulo>
        </detalle_factura>
    </factura>
</facturas>
