=== AlexRA95/Proyectos/HTML2024/2ºEVA/cuentos/cuento1.dtd
<!ELEMENT cuento (personajes,trama,etiqueta*)>
    <!ATTLIST cuento cod ID #REQUIRED> <!-- Tiene que ser 1 letra y 2 numeros-->
    <!ATTLIST cuento titulo CDATA #REQUIRED>
    <!ATTLIST cuento genero (infantil|fantasia|terror) #IMPLIED>
<!ELEMENT personajes (personaje+)>
<!ELEMENT personaje (nombre,genero,descripcion?)>
    <!ATTLIST personaje id ID #REQUIRED>
    <!ATTLIST personaje tipo (principal |secundario |antagonista ) "principal"> 
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)> <!-- Solo puede ser M, F o N-->
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT trama (#PCDATA)>
<!ELEMENT etiqueta EMPTY>
    <!ATTLIST etiqueta nombre CDATA #REQUIRED>

=== AlexRA95/Proyectos/HTML2024/2ºEVA/cuentos/cuento1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cuento SYSTEM "cuento1.dtd">
<cuento cod="L11" titulo="La Cenicienta" genero="infantil">
    <personajes>
        <personaje id="CEN" tipo="principal">
            <nombre>Ceninicenta</nombre>
            <genero>F</genero>
            <descripcion>Una joven trabajadora y bondadosa</descripcion>
        </personaje>
        <personaje id="MAD" tipo="antagonista">
            <nombre>Madrastra</nombre>
            <genero>F</genero>
        </personaje>
        <personaje id="PRI" tipo="secundario">
            <nombre>Principe</nombre>
            <genero>M</genero>
        </personaje>
    </personajes>
    <trama>Cenicienta, una joven desfavorecida, transforma su suerte con la ayuda de su hada madrina
        y un zapato de cristal para conquistar el corazón del príncipe.</trama>
    <etiqueta nombre="amor"/>
    <etiqueta nombre="superacion"/>
</cuento>
