=== AlexRA95/Proyectos/HTML2024/2ºEVA/schema_xsd/personas/personas.dtd
<!ELEMENT personas (persona)+>
    <!ELEMENT persona (nombre, apellido+, edad?, dni, ((email, telefono?) | (telefono, email?)), direccion, jefe?, caracteristicas?)>
        <!ATTLIST persona idpersona ID #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT jefe EMPTY>
        <!ATTLIST jefe idjefe IDREF #REQUIRED>
    <!ELEMENT caracteristicas (idioma | lenguajeprogramacion)+>
    <!ELEMENT idioma (#PCDATA)>
        <!ATTLIST idioma nivel ( A1 | A2 | B1 | B2 | C1 | C2 ) #IMPLIED>
    <!ELEMENT lenguajeprogramacion (#PCDATA)>

=== AlexRA95/Proyectos/HTML2024/2ºEVA/schema_xsd/personas/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="personas.xsd">
    <persona idpersona="DS-33">
        <nombre>Paca</nombre>
        <apellido>Ortega</apellido>
        <edad>33</edad>
        <dni>09.214.328-E</dni>
        <email>acb@hotmail.com</email>
        <telefono>608677125</telefono>
        <direccion>C/San Manuel, 15</direccion>
        <jefe idjefe="BA-01"/>
        <caracteristicas>
            <idioma nivel="B2">Ingl√©s</idioma>
            <lenguajeprogramacion>Java</lenguajeprogramacion>
        </caracteristicas>
    </persona>

    <persona idpersona="BA-01">
        <nombre>Paca</nombre>
        <apellido>Ortega</apellido>
        <apellido>Lara</apellido>
        <edad>33</edad>
        <dni>09.214.328-E</dni>
        <email>acb@hotmail.com</email>
        <telefono>608677125</telefono>
        <direccion>C/San Manuel, 15</direccion>
        <caracteristicas>
            <lenguajeprogramacion>Java</lenguajeprogramacion>
            <idioma nivel="A1">Frances</idioma>
            <lenguajeprogramacion>Python</lenguajeprogramacion>
        </caracteristicas>
    </persona>

    <persona idpersona="MM-00">
        <nombre>Paca</nombre>
        <apellido>Ortega</apellido>
        <dni>09.214.328-E</dni>
        <email>acb@hotmail.com</email>
        <telefono>608677125</telefono>
        <direccion>C/San Manuel, 15</direccion>
    </persona>
</personas>
